[package]
name = "rust-lambda-cdk"
version = "0.1.0"
edition = "2021"

[dependencies]
lambda_http = "0.13.0"
lambda_runtime = "0.13.0"
serde = "1.0.206"
serde_json = "1.0.122"
tokio = { version = "1", features = ["full"] }
